class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
      """
      You are given two strings s and t.

      String t is generated by random shuffling string s and then add one more letter at a random position.

      Return the letter that was added to t.
      """
      frequency_hash = {}
      for char in s + t:
        frequency_hash[char] = frequency_hash.get(char, 0) + 1
      
      for char in t:
        if frequency_hash[char] % 2:
          return char
